[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
unused_qualifications = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

missing_const_for_fn = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"

[workspace.dependencies]
anyhow              = { version = "1.0.71", features = ["backtrace"] }
bumpalo             = { version = "3.13.0" }
camino              = { version = "1.1.4"  }
codespan-reporting  = { version = "0.11.1" }
fxhash              = { version = "0.2.1"  }
lasso               = { version = "0.7.2",  features = ["multi-threaded"] }
string32            = { version = "0.2.0"  }
triomphe            = { version = "0.1.8"  }
