[package]
name = "pion"

edition = "2021"
version = "0.1.0"

[lints.rust]
unused_qualifications = { level = "warn", priority = 100 }

[lints.rustdoc]
all = { level = "warn", priority = 0 }

[lints.clippy]
all      = { level = "warn", priority = 0 }
nursery  = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }

match_bool               = { level = "allow", priority = 100 }
missing_errors_doc       = { level = "allow", priority = 100 }
missing_panics_doc       = { level = "allow", priority = 100 }
module_name_repetitions  = { level = "allow", priority = 100 }
must_use_candidate       = { level = "allow", priority = 100 }
option_if_let_else       = { level = "allow", priority = 100 }
return_self_not_must_use = { level = "allow", priority = 100 }
too_many_lines           = { level = "allow", priority = 100 }

[dependencies]
bumpalo            = { version = "3.15.4", features = ["allocator_api"] }
camino             = { version = "1.1.6" }
clap               = { version = "4.5.4", features = ["derive"] }
codespan-reporting = { version = "0.11.1" }
ecow               = { version = "0.2.2" }
either             = { version = "1.10.0" }
internal-iterator  = { version = "0.2.3" }
lalrpop-util       = { version = "0.20.2", default-features = false }
lasso              = { version = "0.7.2", features = ["multi-threaded"] }
logos              = { version = "0.14.0" }
once_cell          = { version = "1.19.0", features = ["parking_lot"] }
pretty             = { version = "0.12.3" }
smallvec           = { version = "1.13.2", features = ["union"] }
text-size          = { version = "1.1.1" }

[build-dependencies]
lalrpop = { version = "0.20.2", default-features = false }

[dev-dependencies]
expect-test = { version = "1.4.1" }

[profile.dev]
opt-level = 0

debug            = 0
debug-assertions = true
overflow-checks  = true
panic            = "abort"
strip            = "debuginfo"

codegen-units = 256
incremental   = true

lto = false

[profile.release]
opt-level = 3

debug            = 0
debug-assertions = false
overflow-checks  = false
panic            = "abort"
strip            = "debuginfo"

codegen-units = 16
incremental   = false

lto = "thin"
