[workspace]
members  = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.rust]
unused_qualifications = { level = "warn", priority = 100 }

[workspace.lints.clippy]
all      = { level = "warn", priority = 0 }
nursery  = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }

match_bool              = { level = "allow", priority = 100 }
missing_const_for_fn    = { level = "allow", priority = 100 }
missing_errors_doc      = { level = "allow", priority = 100 }
missing_panics_doc      = { level = "allow", priority = 100 }
module_name_repetitions = { level = "allow", priority = 100 }
must_use_candidate      = { level = "allow", priority = 100 }
option_if_let_else      = { level = "allow", priority = 100 }
single_match_else       = { level = "allow", priority = 100 }
too_many_lines          = { level = "allow", priority = 100 }
wildcard_imports        = { level = "allow", priority = 100 }

[workspace.dependencies]
anyhow             = { version = "1.0.71", features = ["backtrace"] }
bumpalo            = { version = "3.13.0" }
camino             = { version = "1.1.4" }
codespan-reporting = { version = "0.11.1" }
fxhash             = { version = "0.2.1" }
internal-iterator  = { version = "0.2.1" }
lasso              = { version = "0.7.2", features = ["multi-threaded"] }
nohash             = { version = "0.2.0" }
string32           = { version = "0.2.0" }
triomphe           = { version = "0.1.8" }

[profile.release]
lto = "fat"

[profile.profiling]
debug    = "full"
inherits = "release"
