condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "module"
use_field_init_shorthand = true
wrap_comments = true
