[package]
name = "pion-core"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
pion-hir     = { path = "../pion-hir" }
pion-surface = { path = "../pion-surface" }
pion-utils   = { path = "../pion-utils" }

bumpalo            = { workspace = true }
codespan-reporting = { workspace = true }
cov-mark           = { version = "1.1.0", features = ["thread-local"] }
either             = { version = "1.9.0" }
internal-iterator  = { workspace = true }
nohash             = { workspace = true }
pretty             = { version = "0.12.1" }
string32           = { workspace = true }
triomphe           = { workspace = true }

[dev-dependencies]
expect-test = { version = "1.4.1" }
