[package]
name = "pion-surface"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
pion-utils = { path = "../pion-utils" }
pion-lexer = { path = "../pion-lexer" }

lalrpop-util    = { version = "0.20.0" }
bumpalo         = { version = "3.13.0" }

[build-dependencies]
lalrpop         = { version = "0.20.0", default-features = false } # disable regex support
