[package]
name = "pion"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
pion-language-server = { path = "../pion-language-server" }
pion-lexer           = { path = "../pion-lexer" }
pion-surface         = { path = "../pion-surface" }
pion-utils           = { path = "../pion-utils" }

anyhow             = { workspace = true }
bumpalo            = { workspace = true }
clap               = { version = "4.3.12",  features = ["derive"] }
codespan-reporting = { workspace = true }
