[package]
name = "pion"

edition = { workspace = true }
version = { workspace = true }

[[test]]
name = "integration_tests"

[lints]
workspace = true

[dependencies]
pion-core            = { path = "../pion-core" }
pion-hir             = { path = "../pion-hir" }
pion-language-server = { path = "../pion-language-server" }
pion-lexer           = { path = "../pion-lexer" }
pion-surface         = { path = "../pion-surface" }
pion-utils           = { path = "../pion-utils" }

anyhow             = { workspace = true }
bumpalo            = { workspace = true }
camino             = { workspace = true }
clap               = { version = "4.3.12", features = ["derive"] }
codespan-reporting = { workspace = true }
tikv-jemallocator  = { version = "0.5.4" }

[dev-dependencies]
snapbox = { version = "0.4.11", features = ["harness"] }
