[package]
name = "pion"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
pion-utils = { path = "../pion-utils" }
pion-lexer = { path = "../pion-lexer" }
pion-language-server = { path = "../pion-language-server" }

anyhow     = { workspace = true }
clap       = { version = "4.3.3",  features = ["derive"] }
ariadne    = { version = "0.3.0" }
